### ISSUE TITLE
Yosemite issue

### ISSUE THREAD

**Issue by adcmtc** [Aeon/sidebarFinagler#1]
There seems to be an issue with this for Yosemite.  The default Airdrop sidebar entry throw up an error and the sidebar does not appear to get updated.

<img width="923" alt="screen shot 2015-10-03 at 12 02 51" src="https://cloud.githubusercontent.com/assets/14952486/10262602/c00f7a80-69c6-11e5-8b96-02b6622c54f7.png">

I can get the favourite.txt file and modify existing Sidebar Entries but adding new brand (extra) entries does not seem to work.  IS that a limitation?

**Comment by Aeon** [comment]
It should now ignore special bookmarks like AirDrop or iCloud (basically, any bookmark that does not have an associated path)

As for adding support for inserting brand new entries, let me look into that.

**Comment by Aeon** [comment]
just pushed v0.3, it should work okay for adding new bookmarks to sidebar as well.

@greatkemo, @MarcFowler, @mattdefoor, @postprefix - i note you have forked the repo, if this update is useful to you, let me know :)
- Anton
