### ISSUE TITLE
Mechanism to delete a built-in Favorite?

### ISSUE THREAD

**Issue by jimratliff** [Aeon/sidebarFinagler#2]
The "How do I use it?" documentation says how to (a) keep a Favorite unchanged (delete it), (b) modify a Favorite by changing its path or name, and (c) add a new entry.

Is there a way to remove a Favorite so that it doesn't show in the sidebar?

I'm particularly interested in removing:
AirDrop, All My Files, iCloud Drive, Desktop, and Documents.

**Comment by Aeon** [comment]
@jimratliff you can manage the built-in favorites via Finder Preferences. I would not try using this tool for that, the built-in favorites may be special in some way that this tool does not account for - much safer to use the Preferences dialog for them.

![image](https://cloud.githubusercontent.com/assets/2532/17834253/4e1cae6a-66ec-11e6-87d6-c5931894d55d.png)
